-- MySQL Script generated by MySQL Workbench
-- Fri 28 Feb 2020 06:52:18 PM EST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema KsuSports
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema KsuSports
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `KsuSports` DEFAULT CHARACTER SET utf8 ;
USE `KsuSports` ;

-- -----------------------------------------------------
-- Table `KsuSports`.`mbbTeamStats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KsuSports`.`mbbTeamStats` (
  `record` VARCHAR(256) NOT NULL,
  `last10` MEDIUMTEXT NOT NULL,
  `currentStreak` MEDIUMTEXT NOT NULL,
  `points` FLOAT NOT NULL,
  `scoringMargin` FLOAT NOT NULL,
  `fieldGoalM` FLOAT NOT NULL,
  `fieldGoalA` FLOAT NOT NULL,
  `3ptM` FLOAT NOT NULL,
  `3ptA` FLOAT NOT NULL,
  `ftM` FLOAT NOT NULL,
  `ftA` FLOAT NOT NULL,
  `rebs` FLOAT NOT NULL,
  `rebMargin` FLOAT NOT NULL,
  `asts` FLOAT NOT NULL,
  `tos` FLOAT NOT NULL,
  `toMargin` FLOAT NOT NULL,
  `pointsOffTos` FLOAT NOT NULL,
  `steals` FLOAT NOT NULL,
  `blocks` FLOAT NOT NULL,
  `attendance` FLOAT NOT NULL,
  PRIMARY KEY (`record`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KsuSports`.`mbbRoster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KsuSports`.`mbbRoster` (
  `jerseyNo` INT NOT NULL,
  `picFileName` VARCHAR(256) NOT NULL,
  `firstName` VARCHAR(256) NOT NULL,
  `lastName` VARCHAR(256) NOT NULL,
  `playerYear` INT NOT NULL,
  `playerHeight` VARCHAR(256) NOT NULL,
  `position` VARCHAR(256) NOT NULL,
  `hometown` VARCHAR(256) NOT NULL,
  `highSchool` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`jerseyNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KsuSports`.`mbbPlayerStats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KsuSports`.`mbbPlayerStats` (
  `jerseyNo` INT NOT NULL,
  `gamesPlayed` INT NULL,
  `gamesStarted` INT NULL,
  `minutesPlayed` FLOAT NULL,
  `points` FLOAT NULL,
  `fieldGoalM` FLOAT NULL,
  `fieldGoalA` FLOAT NULL,
  `3ptM` FLOAT NULL,
  `3ptA` FLOAT NULL,
  `ftM` FLOAT NULL,
  `ftA` FLOAT NULL,
  `oReb` FLOAT NULL,
  `dReb` FLOAT NULL,
  `personalFouls` FLOAT NULL,
  `asts` FLOAT NULL,
  `tos` FLOAT NULL,
  `blocks` FLOAT NULL,
  `steals` FLOAT NULL,
  PRIMARY KEY (`jerseyNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KsuSports`.`wbbRoster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KsuSports`.`wbbRoster` (
  `jerseyNo` INT NOT NULL,
  `picFileName` VARCHAR(256) NOT NULL,
  `firstName` VARCHAR(256) NOT NULL,
  `lastName` VARCHAR(256) NOT NULL,
  `playerYear` INT NOT NULL,
  `playerHeight` VARCHAR(256) NOT NULL,
  `position` VARCHAR(256) NOT NULL,
  `hometown` VARCHAR(256) NOT NULL,
  `highSchool` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`jerseyNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KsuSports`.`wbbPlayerStats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KsuSports`.`wbbPlayerStats` (
  `jerseyNo` INT NOT NULL,
  `gamesPlayed` INT NULL,
  `gamesStarted` INT NULL,
  `minutesPlayed` FLOAT NULL,
  `points` FLOAT NULL,
  `fieldGoalM` FLOAT NULL,
  `fieldGoalA` FLOAT NULL,
  `3ptM` FLOAT NULL,
  `3ptA` FLOAT NULL,
  `ftM` FLOAT NULL,
  `ftA` FLOAT NULL,
  `oReb` FLOAT NULL,
  `dReb` FLOAT NULL,
  `personalFouls` FLOAT NULL,
  `asts` FLOAT NULL,
  `tos` FLOAT NULL,
  `blocks` FLOAT NULL,
  `steals` FLOAT NULL,
  PRIMARY KEY (`jerseyNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KsuSports`.`wbbTeamStats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KsuSports`.`wbbTeamStats` (
  `record` VARCHAR(256) NOT NULL,
  `last10` VARCHAR(256) NOT NULL,
  `currentStreak` VARCHAR(256) NOT NULL,
  `points` FLOAT NOT NULL,
  `scoringMargin` FLOAT NOT NULL,
  `fieldGoalM` FLOAT NOT NULL,
  `fieldGoalA` FLOAT NOT NULL,
  `3ptM` FLOAT NOT NULL,
  `3ptA` FLOAT NOT NULL,
  `ftM` FLOAT NOT NULL,
  `ftA` FLOAT NOT NULL,
  `rebs` FLOAT NOT NULL,
  `rebMargin` FLOAT NOT NULL,
  `asts` FLOAT NOT NULL,
  `tos` FLOAT NOT NULL,
  `toMargin` FLOAT NOT NULL,
  `pointsOffTos` FLOAT NOT NULL,
  `steals` FLOAT NOT NULL,
  `blocks` FLOAT NOT NULL,
  `attendance` FLOAT NOT NULL,
  `playerJerseys` VARCHAR(45) NULL,
  PRIMARY KEY (`record`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KsuSports`.`baseballRoster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KsuSports`.`baseballRoster` (
  `jerseyNo` INT NOT NULL,
  `picFileName` VARCHAR(256) NOT NULL,
  `firstName` VARCHAR(256) NOT NULL,
  `lastName` VARCHAR(256) NOT NULL,
  `playerYear` INT NOT NULL,
  `playerHeight` VARCHAR(256) NOT NULL,
  `playerWeight` INT NOT NULL,
  `position` VARCHAR(256) NOT NULL,
  `hometown` VARCHAR(256) NOT NULL,
  `highSchool` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`jerseyNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KsuSports`.`baseballBattingStats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KsuSports`.`baseballBattingStats` (
  `jerseyNo` INT NOT NULL,
  `gamesPlayed` INT NULL,
  `gamesStarted` INT NULL,
  `atBats` FLOAT NULL,
  `runs` FLOAT NULL,
  `hits` FLOAT NULL,
  `doubles` FLOAT NULL,
  `triples` FLOAT NULL,
  `homeRuns` FLOAT NULL,
  `rbis` FLOAT NULL,
  `totalBases` FLOAT NULL,
  `walks` FLOAT NULL,
  `hbps` FLOAT NULL,
  `strikeOuts` FLOAT NULL,
  `gdps` FLOAT NULL,
  `sfbs` FLOAT NULL,
  `shs` FLOAT NULL,
  `sbs` FLOAT NULL,
  `sbAttempts` FLOAT NULL,
  PRIMARY KEY (`jerseyNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KsuSports`.`baseballPitchingStats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KsuSports`.`baseballPitchingStats` (
  `jerseyNo` INT NOT NULL,
  `wins` FLOAT NULL,
  `losses` FLOAT NULL,
  `appearances` FLOAT NULL,
  `gamesStarted` FLOAT NULL,
  `completeGames` FLOAT NULL,
  `shutOuts` FLOAT NULL,
  `saves` FLOAT NULL,
  `inningsPitched` FLOAT NULL,
  `hitsAllowed` FLOAT NULL,
  `runsAllowed` FLOAT NULL,
  `eras` FLOAT NULL,
  `walks` FLOAT NULL,
  `strikeouts` FLOAT NULL,
  `doublesAllowed` FLOAT NULL,
  `triplesAllowed` FLOAT NULL,
  `hrsAllowed` FLOAT NULL,
  `atBats` FLOAT NULL,
  `wildPitches` FLOAT NULL,
  `hbps` FLOAT NULL,
  `balks` FLOAT NULL,
  `sfsAllowed` FLOAT NULL,
  `shsAllowed` FLOAT NULL,
  PRIMARY KEY (`jerseyNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KsuSports`.`baseballFieldingStats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KsuSports`.`baseballFieldingStats` (
  `jerseyNo` INT NOT NULL,
  `chances` FLOAT NULL,
  `putouts` FLOAT NULL,
  `assists` FLOAT NULL,
  `errors` FLOAT NULL,
  `doublePlays` FLOAT NULL,
  `stolenBaseAttempts` FLOAT NULL,
  `stolenBasesCaught` FLOAT NULL,
  `passedBalls` FLOAT NULL,
  `cis` FLOAT NULL,
  PRIMARY KEY (`jerseyNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KsuSports`.`softballRoster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KsuSports`.`softballRoster` (
  `jerseyNo` INT NOT NULL,
  `picFileName` VARCHAR(256) NOT NULL,
  `firstName` VARCHAR(256) NOT NULL,
  `lastName` VARCHAR(256) NOT NULL,
  `playerYear` INT NOT NULL,
  `playerHeight` VARCHAR(256) NOT NULL,
  `playerWeight` INT NOT NULL,
  `position` VARCHAR(256) NOT NULL,
  `hometown` VARCHAR(256) NOT NULL,
  `highSchool` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`jerseyNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KsuSports`.`softballBattingStats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KsuSports`.`softballBattingStats` (
  `jerseyNo` INT NOT NULL,
  `gamesPlayed` INT NULL,
  `gamesStarted` INT NULL,
  `atBats` FLOAT NULL,
  `runs` FLOAT NULL,
  `hits` FLOAT NULL,
  `doubles` FLOAT NULL,
  `triples` FLOAT NULL,
  `homeRuns` FLOAT NULL,
  `rbis` FLOAT NULL,
  `totalBases` FLOAT NULL,
  `walks` FLOAT NULL,
  `hbps` FLOAT NULL,
  `strikeOuts` FLOAT NULL,
  `gdps` FLOAT NULL,
  `sfbs` FLOAT NULL,
  `shs` FLOAT NULL,
  `sbs` FLOAT NULL,
  `sbAttempts` FLOAT NULL,
  PRIMARY KEY (`jerseyNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KsuSports`.`softballFieldingStats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KsuSports`.`softballFieldingStats` (
  `jerseyNo` INT NOT NULL,
  `chances` FLOAT NULL,
  `putouts` FLOAT NULL,
  `assists` FLOAT NULL,
  `errors` FLOAT NULL,
  `doublePlays` FLOAT NULL,
  `stolenBaseAttempts` FLOAT NULL,
  `stolenBasesCaught` FLOAT NULL,
  `passedBalls` FLOAT NULL,
  `cis` FLOAT NULL,
  PRIMARY KEY (`jerseyNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KsuSports`.`softballPitchingStats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KsuSports`.`softballPitchingStats` (
  `jerseyNo` INT NOT NULL,
  `wins` FLOAT NULL,
  `losses` FLOAT NULL,
  `appearances` FLOAT NULL,
  `gamesStarted` FLOAT NULL,
  `completeGames` FLOAT NULL,
  `shutOuts` FLOAT NULL,
  `saves` FLOAT NULL,
  `inningsPitched` FLOAT NULL,
  `hitsAllowed` FLOAT NULL,
  `runsAllowed` FLOAT NULL,
  `eras` FLOAT NULL,
  `walks` FLOAT NULL,
  `strikeouts` FLOAT NULL,
  `doublesAllowed` FLOAT NULL,
  `triplesAllowed` FLOAT NULL,
  `hrsAllowed` FLOAT NULL,
  `atBats` FLOAT NULL,
  `wildPitches` FLOAT NULL,
  `hbps` FLOAT NULL,
  `balks` FLOAT NULL,
  `sfsAllowed` FLOAT NULL,
  `shsAllowed` FLOAT NULL,
  PRIMARY KEY (`jerseyNo`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;